export const KeyPress = {
	// Special
	Backspace: { key: 'Backspace', code: 'Backspace', keyCode: 8, charCode: 8 },
	Tab: { key: 'Tab', code: 'Tab', keyCode: 9, charCode: 9 },
	Enter: { key: 'Enter', code: 'Enter', keyCode: 13, charCode: 13 },
	Shift: { key: 'Shift', code: 'Shift', keyCode: 16, charCode: 16 },
	Control: { key: 'Control', code: 'Control', keyCode: 17, charCode: 17 },
	Alt: { key: 'Alt', code: 'Alt', keyCode: 18, charCode: 18 },
	CapsLock: { key: 'CapsLock', code: 'CapsLock', keyCode: 20, charCode: 20 },
	Escape: { key: 'Escape', code: 'Escape', keyCode: 27, charCode: 27 },
	Space: { key: ' ', code: 'Space', keyCode: 32, charCode: 32 },
	PageUp: { key: 'PageUp', code: 'PageUp', keyCode: 33, charCode: 33 },
	PageDown: { key: 'PageDown', code: 'PageDown', keyCode: 34, charCode: 34 },
	End: { key: 'End', code: 'End', keyCode: 35, charCode: 35 },
	Home: { key: 'Home', code: 'Home', keyCode: 36, charCode: 36 },
	ArrowLeft: { key: 'ArrowLeft', code: 'ArrowLeft', keyCode: 37, charCode: 37 },
	ArrowUp: { key: 'ArrowUp', code: 'ArrowUp', keyCode: 38, charCode: 38 },
	ArrowRight: { key: 'ArrowRight', code: 'ArrowRight', keyCode: 39, charCode: 39 },
	ArrowDown: { key: 'ArrowDown', code: 'ArrowDown', keyCode: 40, charCode: 40 },
	Delete: { key: 'Delete', code: 'Delete', keyCode: 46, charCode: 46 },

	// Numbers
	0: { key: '0', code: 'Digit0', keyCode: 48, charCode: 48 },
	1: { key: '1', code: 'Digit1', keyCode: 49, charCode: 49 },
	2: { key: '2', code: 'Digit2', keyCode: 50, charCode: 50 },
	3: { key: '3', code: 'Digit3', keyCode: 51, charCode: 51 },
	4: { key: '4', code: 'Digit4', keyCode: 52, charCode: 52 },
	5: { key: '5', code: 'Digit5', keyCode: 53, charCode: 53 },
	6: { key: '6', code: 'Digit6', keyCode: 54, charCode: 54 },
	7: { key: '7', code: 'Digit7', keyCode: 55, charCode: 55 },
	8: { key: '8', code: 'Digit8', keyCode: 56, charCode: 56 },
	9: { key: '9', code: 'Digit9', keyCode: 57, charCode: 57 },

	A: { key: 'A', code: 'KeyA', keyCode: 65, charCode: 65 },
	B: { key: 'B', code: 'KeyB', keyCode: 66, charCode: 66 },
	C: { key: 'C', code: 'KeyC', keyCode: 67, charCode: 67 },
	D: { key: 'D', code: 'KeyD', keyCode: 68, charCode: 68 },
	E: { key: 'E', code: 'KeyE', keyCode: 69, charCode: 69 },
	F: { key: 'F', code: 'KeyF', keyCode: 70, charCode: 70 },
	G: { key: 'G', code: 'KeyG', keyCode: 71, charCode: 71 },
	H: { key: 'H', code: 'KeyH', keyCode: 72, charCode: 72 },
	I: { key: 'I', code: 'KeyI', keyCode: 73, charCode: 73 },
	J: { key: 'J', code: 'KeyJ', keyCode: 74, charCode: 74 },
	K: { key: 'K', code: 'KeyK', keyCode: 75, charCode: 75 },
	L: { key: 'L', code: 'KeyL', keyCode: 76, charCode: 76 },
	M: { key: 'M', code: 'KeyM', keyCode: 77, charCode: 77 },
	N: { key: 'N', code: 'KeyN', keyCode: 78, charCode: 78 },
	O: { key: 'O', code: 'KeyO', keyCode: 79, charCode: 79 },
	P: { key: 'P', code: 'KeyP', keyCode: 80, charCode: 80 },
	Q: { key: 'Q', code: 'KeyQ', keyCode: 81, charCode: 81 },
	R: { key: 'R', code: 'KeyR', keyCode: 82, charCode: 82 },
	S: { key: 'S', code: 'KeyS', keyCode: 83, charCode: 83 },
	T: { key: 'T', code: 'KeyT', keyCode: 84, charCode: 84 },
	U: { key: 'U', code: 'KeyU', keyCode: 85, charCode: 85 },
	V: { key: 'V', code: 'KeyV', keyCode: 86, charCode: 86 },
	W: { key: 'W', code: 'KeyW', keyCode: 87, charCode: 87 },
	X: { key: 'X', code: 'KeyX', keyCode: 88, charCode: 88 },
	Y: { key: 'Y', code: 'KeyY', keyCode: 89, charCode: 89 },
	Z: { key: 'Z', code: 'KeyZ', keyCode: 90, charCode: 90 },
};
